// Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Prob Link: https://leetcode.com/problems/find-the-difference/

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> mp;
        for(auto it: t){
            mp[it]++;
        }
        for(auto it: s){
            mp[it]--;
        }
        char ans;
        for(auto it: mp){
            if(it.second > 0){
                ans = it.first;
            }
        }
        return ans;
    }
};